<?php
/**
 * Copyright © 2015 UberTheme. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
require(["jquery", "prototype"], function(jQuery){
    
    function showHideContentFields()
    {
        if ($('item_content_type')){
            if ($('item_content_type').value != 'image') {
                $('item_video_id').up('div.field').show();
                $('item_video_id').addClassName('required-entry');
                $('item_image').up('div.field').hide();
                $('item_image').removeClassName('required-entry');
            } else {
                $('item_video_id').up('div.field').hide();
                $('item_video_id').removeClassName('required-entry');
                $('item_image').up('div.field').show();
                if (!$('item_image').readAttribute('value').length){
                    $('item_image').addClassName('required-entry');    
                }
            }
        }
        return true;
    }
    jQuery(document).ready(showHideContentFields);
    window.showHideContentFields = showHideContentFields;

    //auto select video type after fill video link
    jQuery('#item_link').on('blur', function(){
        var link = jQuery(this).val();
        if (/youtu.be/i.test(link)){
            jQuery("#item_content_type").val('youtube_video');
        } else if (/vimeo.com/i.test(link)) {
            jQuery("#item_content_type").val('vimeo_video');
        }
        jQuery("#item_content_type").change();
    });
});
</script>
