<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Feed
 */
?>
<?php $_value       = $block->getElement()->getCsvField()?>
<?php $_htmlId      = $block->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $block->getElement()->getClass() ?>
<?php $_htmlName    = $block->getElement()->getName() ?>
<?php $_readonly    = $block->getElement()->getReadonly() ?>
<div class="field" id="attribute-<?php echo $_htmlId?>-container">
<!--    <label class="label"><span>--><?php //echo $block->getElement()->getLabel(); ?><!--</span></label>-->
    <div xclass="control">
    <table class="admin__control-table amasty-csv-table" id="fields_table">
        <thead>
            <tr>
                <th class="required"><?php echo __('Header')?></th>
                <th class="required"><?php echo __('Attribute')?></th>
                <th class="required"><?php echo __('Format')?></th>
                <th class="required"><?php echo __('Parent')?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody id="<?php echo $_htmlId; ?>_container"></tbody>
        <tfoot>
             <tr>
                <td colspan="6" class="col-actions-add"><?php echo $block->getAddAttributeButtonHtml(); ?>&nbsp;<?php echo $block->getAddStaticTextButtonHtml(); ?></td>
            </tr>
        </tfoot>
    </table>
    </div>
</div>
    <script>
    require([
        'mage/template',
        "prototype",
        "mage/adminhtml/form"
    ], function (mageTemplate, jquery) {
        //<![CDATA[
            var fieldRowTemplate = '<tr>'
            + '<td><input id="field_row_<%- data.index %>_header" name="<?php echo $_htmlName; ?>[<%- data.index %>][header]" class="<?php echo $_htmlClass; ?> required-entry"/></td>'
            + '<td><select id="field_row_<%- data.index %>_attribute" class="<?php echo $_htmlClass; ?> required-entry" name="<?php echo $_htmlName; ?>[<%- data.index %>][attribute]" >'
            + '<optgroup label="<?php echo __("Basic"); ?>">'
            <?php foreach ($block->getBasicAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?php echo $_attributeId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_attributeName)); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?php echo __("Product"); ?>">'
            <?php foreach ($block->getProductAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?php echo $_attributeId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_attributeName)); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?php echo __("Inventory"); ?>">'
            <?php foreach ($block->getInventoryAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?php echo $_attributeId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_attributeName)); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?php echo __("Price"); ?>">'
            <?php foreach ($block->getPriceAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?php echo $_attributeId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_attributeName)); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?php echo __("Category"); ?>">'
            <?php foreach ($block->getCategoryAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?php echo $_attributeId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_attributeName)); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?php echo __("Category Paths"); ?>">'
            <?php foreach ($block->getCategoryPathsAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?php echo $_attributeId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_attributeName)); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?php echo __("Image"); ?>">'
            <?php foreach ($block->getImageAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?php echo $_attributeId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_attributeName)); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?php echo __("Gallery"); ?>">'
            <?php foreach ($block->getGalleryAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?php echo $_attributeId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_attributeName)); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '<optgroup label="<?php echo __("Url"); ?>">'
            <?php foreach ($block->getUrlAttributes() as $_attributeId => $_attributeName): ?>
            + '<option value="<?php echo $_attributeId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_attributeName)); ?></option>'
            <?php endforeach; ?>
            + '</optgroup>'
            + '</select></td>'
            + '<td><select id="field_row_<%- data.index %>_format" class="<?php echo $_htmlClass; ?> required-entry" name="<?php echo $_htmlName; ?>[<%- data.index %>][format]" >'
            <?php foreach ($block->getFormats() as $_formatId => $_formatName): ?>
            + '<option value="<?php echo $_formatId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_formatName)); ?></option>'
            <?php endforeach; ?>
            + '</select></td>'
            + '<td><select id="field_row_<%- data.index %>_parent" class="<?php echo $_htmlClass; ?> required-entry" name="<?php echo $_htmlName; ?>[<%- data.index %>][parent]" >'
            <?php foreach ($block->getParentsVars() as $_formatId => $_formatName): ?>
            + '<option value="<?php echo $_formatId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_formatName)); ?></option>'
            <?php endforeach; ?>
            + '</select></td>'
            + '<td class="col-delete"><input type="hidden" name="<?php echo $_htmlName; ?>[<%- data.index %>][delete]" class="delete" value="" id="field_row_<%- data.index %>_delete" />'
            + '<button title="<?php echo __('Delete'); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="field_row_<%- data.index %>_delete_button" onclick="return fieldControl.deleteAttribute(event, <%- data.index %>);">'
            + '<span><?php echo __('Delete'); ?></span></button>'

            + '</td>'
            + '</tr>'
            + '<tr><td class="amasty-modify-cell" colspan=5><table id="field_row_<%- data.index %>_modify_container"></table>'
            + '<a id="amasty_modify_link_hide_<%- data.index %>" class="amasty-modify-link amasty-hide-link" href="#" onclick="fieldControl.hideModifiers(<%- data.index %>); return false;">'
            + '<?php echo __('hide modifier(s)'); ?>'
            + '</a>'
            + '<a id="amasty_modify_link_add_<%- data.index %>" class="amasty-modify-link" href="#" onclick="fieldControl.modifyItem(<%- data.index %>); return false;">'
            + '<?php echo __('add modifier'); ?>'
            + '</a>'
            + '<a id="amasty_modify_link_show_<%- data.index %>" class="amasty-modify-link" href="#" onclick="fieldControl.showModifiers(<%- data.index %>); return false;">'
            + '<?php echo __('show modifier(s)'); ?>'
            + '</a>'
            + '</td></tr>';

            var modifyTemplate = '<tr>'
            + '<td class="amasty-modify">'
            + '<select onchange="return fieldControl.changeModifier(this);" id="field_row_<%- data.rowIndex %>_<%- data.index %>_modify" class="<?php echo $_htmlClass; ?> required-entry" name="<?php echo $_htmlName; ?>[<%- data.rowIndex %>][modify][<%- data.index %>][modify]">'
            <?php foreach ($block->getModiftVars() as $_modifyId => $_modifyName): ?>
            + '<option value="<?php echo $_modifyId; ?>"><?php echo $block->escapeQuote($block->escapeHtml($_modifyName)); ?></option>'
            <?php endforeach; ?>
            + '</select>'
            + '<input style="display: none;" id="field_row_<%- data.rowIndex %>_<%- data.index %>_arg0" name="<?php echo $_htmlName; ?>[<%- data.rowIndex %>][modify][<%- data.index %>][arg0]" class="<?php echo $_htmlClass; ?>"/>'
            + '<input style="display: none;" id="field_row_<%- data.rowIndex %>_<%- data.index %>_arg1" name="<?php echo $_htmlName; ?>[<%- data.rowIndex %>][modify][<%- data.index %>][arg1]" class="<?php echo $_htmlClass; ?>"/>'
            + '<button title="<?php echo __('Delete'); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="field_row_<%- data.rowIndex %>_<%- data.index %>_delete_button" onclick="return fieldControl.deleteItem(event);" >'
            + '<span><?php echo __('Delete'); ?></span></button>'
            + '</td>'
            + '</tr>';

            var staticTextRowTemplate = '<tr>'
            + '<td><input id="field_row_<%- data.index %>_header" name="<?php echo $_htmlName; ?>[<%- data.index %>][header]" class="<?php echo $_htmlClass; ?> required-entry"/></td>'
            + '<td colspan=3><input id="field_row_<%- data.index %>_static_text" class="<?php echo $_htmlClass; ?> required-entry" name="<?php echo $_htmlName; ?>[<%- data.index %>][static_text]" />'
            + '</td>'
            + '<td class="col-delete"><input type="hidden" name="<?php echo $_htmlName; ?>[<%- data.index %>][delete]" class="delete" value="" id="field_row_<%- data.index %>_delete" />'
            + '<button title="<?php echo __('Delete'); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="field_row_<%- data.index %>_delete_button" onclick="return fieldControl.deleteItem(event);">'
            + '<span><?php echo __('Delete'); ?></span></button>'
            + '</td>'
            + '</tr>';

        var fieldControl = {
            rowTemplate: mageTemplate(fieldRowTemplate),
            modifyTemplate: mageTemplate(modifyTemplate),
            staticTextRowTemplate: mageTemplate(staticTextRowTemplate),
            itemsCount: 0,
            modifyCount: 0,
            argsConfig: <?php echo json_encode($this->getArgs())?>,
            addItem: function (header, attribute, format, parent) {


                var data = {
                    index: this.itemsCount++
                };

                Element.insert($('<?php echo $_htmlId; ?>_container'), {
                    bottom : this.rowTemplate({
                        data: data
                    })
                });

                if (header)
                    $('field_row_' + data.index + '_header').value = header;

                if (attribute)
                    $('field_row_' + data.index + '_attribute').value = attribute;

                if (format)
                    $('field_row_' + data.index + '_format').value = format;

                if (parent)
                    $('field_row_' + data.index + '_parent').value = parent;

                var linkHide = $("amasty_modify_link_hide_" + data.index);
                var linkShow = $("amasty_modify_link_show_" + data.index);

                linkHide.hide();
                linkShow.hide();

                return data.index;

            },
            addStaticTextItem: function(header, text){
                var data = {
                    index: this.itemsCount++
                };

                Element.insert($('<?php echo $_htmlId; ?>_container'), {
                    bottom : this.staticTextRowTemplate({
                        data: data
                    })
                });

                if (header)
                    $('field_row_' + data.index + '_header').value = header;

                if (text)
                    $('field_row_' + data.index + '_static_text').value = text;

                return data.index;
            },
            deleteAttribute: function(event, rowIndex){
                $('field_row_' + rowIndex + '_modify_container').up('tr').remove();
                this.deleteItem(event);
            },
            deleteItem: function(event) {
                var tr = Event.findElement(event, 'tr');
                if (tr) {
                    Element.select(tr, ['input', 'select']).each(function(element) {
                        element.remove();
                    });
                    Element.remove(tr);
//                    Element.addClassName(tr, 'no-display template');
                }
                return false;
            },
            modifyItem: function(rowIndex, modify, arg0, arg1){
                var containerId = 'field_row_' + rowIndex +'_modify_container';

                var container = $(containerId);
                var linkHide = $("amasty_modify_link_hide_" + rowIndex);
                var link = $("amasty_modify_link_" + rowIndex);

                if (container) {
                    var data = {
                        index: this.modifyCount++,
                        rowIndex: rowIndex
                    };

                    Element.insert(container, {
                        bottom : this.modifyTemplate({
                            data: data
                        })
                    });

                    if (modify){
                        var modifySelect = $('field_row_' + data.rowIndex + '_' + data.index + '_modify');
                        if (modifySelect) {
                            modifySelect.value = modify;
                            this.changeModifier(modifySelect);
                        }
                    }

                    if (arg0){
                        $('field_row_' + data.rowIndex + '_' + data.index + '_arg0').value = arg0;
                    }

                    if (arg1){
                        $('field_row_' + data.rowIndex + '_' + data.index + '_arg1').value = arg1;
                    }

                    linkHide.show();
                }
            },
            changeModifier: function(select){
//                var select = Event.findElement(event, 'select');
                var td = select.up('td');

                var args = []

                if (this.argsConfig[select.getValue()]){
                    args = this.argsConfig[select.getValue()];
                }

                td.select('input').each(function(input){
                    input.hide();
                });

                for(var idx = 0; idx < args.length; idx++){
                    var id = select.id.replace("_modify", "_arg" + idx)
                    var input = td.down("#" + id);
                    if (input){
                        input.show();
                        input.setAttribute('placeholder', args[idx]);
                    }
                }
            },
            showAddModifyLink: function(rowIndex){
                var $linkAdd = $("amasty_modify_link_add_" + rowIndex);
                var $linkShow = $("amasty_modify_link_show_" + rowIndex);
                var $linkHide = $("amasty_modify_link_hide_" + rowIndex);
                var $container = $("field_row_" + rowIndex + "_modify_container");

//                $container.hide();


                if ($container.select("tr").length > 0 ){
                    $container.hide();
                    $linkShow.show();
                    $linkAdd.hide();
                    $linkHide.hide();

                } else {
                    $linkShow.hide();
                    $linkAdd.show();
                    $linkHide.hide();

                }

            },
            showModifiers: function(rowIndex){
                var $linkAdd = $("amasty_modify_link_add_" + rowIndex);
                var $linkShow = $("amasty_modify_link_show_" + rowIndex);
                var $container = $("field_row_" + rowIndex + "_modify_container");
                var $linkHide = $("amasty_modify_link_hide_" + rowIndex);

                $linkShow.hide();
                $linkAdd.show();
                $linkHide.show()

                $container.show();
            },
            hideModifiers: function(rowIndex){
                var $linkAdd = $("amasty_modify_link_add_" + rowIndex);
                var $linkShow = $("amasty_modify_link_show_" + rowIndex);
                var $container = $("field_row_" + rowIndex + "_modify_container");
                var $linkHide = $("amasty_modify_link_hide_" + rowIndex);

                $linkShow.show();
                $linkAdd.hide();
                $linkHide.hide()

                $container.hide();
            }
        };

        <?php foreach ($_value as $_item) : ?>

        <?php if ($_item['static_text']) :?>
            var rowIndex = fieldControl.addStaticTextItem('<?php echo $this->escapeQuote($_item['header'], true); ?>', '<?php echo $_item['static_text']; ?>');
        <?php else : ?>
            var rowIndex = fieldControl.addItem(
                '<?php echo $this->escapeQuote($_item['header'], true); ?>',
                '<?php echo $this->escapeQuote($_item['attribute'], true); ?>',
                '<?php echo $this->escapeQuote($_item['format'], true); ?>',
                '<?php echo $this->escapeQuote($_item['parent'], true); ?>'
            );
            <?php foreach($_item['modify'] as $_modify) : ?>

            fieldControl.modifyItem(rowIndex,
                '<?php echo $this->escapeQuote($_modify['modify'], true); ?>',
                '<?php echo $this->escapeQuote($_modify['arg0'], true); ?>',
                '<?php echo $this->escapeQuote($_modify['arg1'], true); ?>'
            );

            <?php endforeach; ?>

            fieldControl.showAddModifyLink(rowIndex);
        <?php endif; ?>


        <?php endforeach; ?>

        window.fieldControl = fieldControl;
        //]]>
    });
</script>
