<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
    /** @var \Amasty\Shopby\Model\FilterSetting $filterSetting */
    /** @var \Amasty\Shopby\Block\Navigation\FilterRenderer $block */
?>
<ol class="items am_shopby_filter_items_<?=$filterSetting->getFilterCode();?>">
    <li id="am_shopby_filter_widget_<?php echo $filterSetting->getFilterCode(); ?>">
        <form>
            <div class="range">
                <input class="amshopby-filter-price-from" data-validate="{ 'validate-number':true}" id="am_shopby_filter_widget_<?php echo $filterSetting->getFilterCode(); ?>_from" type="text" class="input-text" placeholder="<?php echo __('From')?>"/>
                <input class="amshopby-filter-price-to" data-validate="{ 'validate-number':true}" id="am_shopby_filter_widget_<?php echo $filterSetting->getFilterCode(); ?>_to" type="text" class="input-text" placeholder="<?php echo __('To')?>"/>
                <button class="amshopby-filter-price-go" id="am_shopby_filter_widget_<?php echo $filterSetting->getFilterCode(); ?>_go"><?php echo __('Go')?></button>
            </div>
        </form>
    </li>
</ol>
<script type="text/x-magento-init">
{
    "#am_shopby_filter_widget_<?php echo $filterSetting->getFilterCode(); ?>": {
        "amShopbyFilterFromTo": {
                "from":"<?php echo $fromToConfig['from'];?>",
                "to":"<?php echo $fromToConfig['to'];?>",
                "min":"<?php echo $fromToConfig['min'];?>",
                "max":"<?php echo $fromToConfig['max'];?>",
                "url": "<?php echo $block->getSliderUrlTemplate(); ?>"
            }
    }
}
</script>
<?php if($filterSetting->isShowTooltip()): ?>
    <?php $tooltipTemplate = '<span class="tooltip amshopby-filter-tooltip" style="float:right" title="{content}"><img src="'.$tooltipUrl.'"</img></span>'; ?>
    <script type="text/x-magento-init">
            {
                ".am_shopby_filter_items_<?php echo $filterSetting->getFilterCode()?>": {
                    "amShopbyFilterAddTooltip": {
                        "content": <?php echo json_encode($filterSetting->getTooltip())?>,
                        "tooltipTemplate": <?php echo json_encode($tooltipTemplate)?>
                    }
                }
            }
    </script>
<?php endif; ?>
