<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Reports\Block\Product\Viewed
 */

//print_r($block->getRecentlyViewedProducts());exit;
?>

<?php
if ($exist = ($block->getRecentlyViewedProducts() && $block->getRecentlyViewedProducts()->getSize())) {
    $type = 'widget-viewed';
    $mode = 'grid';

    $type = $type . '-' . $mode;

    $image = 'recently_viewed_products_grid_content_widget';
    $title = __('Recently Viewed');
    $items = $block->getRecentlyViewedProducts();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $rating = 'short';
    $description = ($mode == 'list') ? true : false;
}
?>
<?php if ($exist):?>
<div class="recently-viewed">
                <h3 class="title-block">Recently Viewed Products</h3>
                <ul>
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <li>
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo $block->escapeHtml($_item->getName()) ?>">
                                        <div class="img-pro">
                                            <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                        </div>
                                <p><span><?php echo $block->escapeHtml($_item->getName()) ?></span></p>
                                </a>
                        </li>
                        <?php endforeach ?>
                </ul>
</div>
<!-- END ecently-viewed -->
    
<?php endif;?>
