<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Category left navigation
 *
 * @var $block \Magento\Catalog\Block\Navigation
 */
?>
<?php if (!$block->getCategory()) {
    return;
} ?>
<?php $_categories = $block->getCurrentChildCategories(); ?>
<?php $_count = is_array($_categories) ? count($_categories) : $_categories->count(); ?>
<?php if ($_count): ?>
<strong class="title"><span>Categories</span></strong>
<ul class="items">
<?php foreach ($_categories as $_category): ?>
    <?php if ($_category->getIsActive()): ?>
        <li class="item">
            <a href="<?php /* @escapeNotVerified */ echo $block->getCategoryUrl($_category) ?>"<?php if ($block->isCategoryActive($_category)): ?> class="current"<?php endif; ?>><?php echo $block->escapeHtml($_category->getName()) ?> <span>(<?php /* @escapeNotVerified */ echo $_category->getProductCount() ?>)</span></a>
            
        </li>
    <?php endif; ?>
<?php endforeach ?>
</ul>
<?php endif; ?>
