<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Feed
 */
?>
<?php $_value       = $block->getElement()->getValue()?>
<?php $_htmlId      = $block->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $block->getElement()->getClass() ?>
<?php $_htmlName    = $block->getElement()->getName() ?>
<?php $_readonly    = $block->getElement()->getReadonly() ?>
<div class="field" id="attribute-<?php echo $_htmlId?>-container">
    <label class="label"><span><?php echo $block->getElement()->getLabel(); ?></span></label>
    <div class="control">
        <ul style="list-style-type: none;">
            <?php foreach($this->getCategoriesList() as $category){
            ?>
                <li style="padding:3px 0px 3px <?php echo ($category['level'] * 30)?>px;">

                    <?php
                     if (isset($_value[$category['id']])){
                         $variable = $_value[$category['id']]['name'];
                     ?>
                         <span>
                             <a href="#" onclick="mappingControl.modify(<?php echo $category['id']?>, '<?php echo $block->escapeJsQuote($block->escapeHtml($variable))?>', '<?php echo $block->escapeJsQuote($block->escapeHtml($category['name']))?>', this); return false;"><?php echo $block->escapeHtml($variable);?></a>
                         </span>
                         <span>&nbsp;(<?php echo $block->escapeHtml($category['name'])?>)</span>
                     <?php
                    } else {
                    ?>
                         <span>
                         <a href="#" onclick="mappingControl.modify(<?php echo $category['id']?>, '', '<?php echo $block->escapeJsQuote($block->escapeHtml($category['name']))?>', this); return false;"><?php     echo $block->escapeHtml($category['name']);?></a>
                         </span>
                    <?php
                    }
                    ?>
                </li>
            <?php
            }?>
        </ul>
    </div>
</div>
    

<script>
  require([
      'mage/template',
      "prototype",
      "mage/adminhtml/form"
  ], function (mageTemplate) {
      //<![CDATA[
          var fieldRowTemplate = '<input class="input-text" type="text" '
          + 'name="<?php echo $_htmlName; ?>[<%- data.id %>][name]" '
          + 'value="<%- data.value %>" '
          + 'placeholder="<%- data.placeholder %>"'
          + '/>';

      var mappingControl = {
          template: mageTemplate(fieldRowTemplate),
          modify: function(id, value, placeholder, link){
              var data = {
                  id: id,
                  value: value,
                  placeholder: placeholder
              };

              $(link).hide();

              Element.insert($(link).up('span'), {
                  bottom : this.template({
                      data: data
                  })
              });
          }
      };

      window.mappingControl = mappingControl;
      //]]>
  });
</script>