<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Tax\Block\Checkout\Tax
 * @see \Magento\Tax\Block\Checkout\Tax
 */
?>
<style type="text/css">
    .tax-title::after {
        color: inherit;
        display: inline-block;
        font-size: 12px;
        font-weight: normal;
        line-height: 12px;
        overflow: hidden;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
    }
    .tax-show {
        content: '+';
        font-size: 12px !important;
        font-weight: normal !important;
        cursor: pointer;
    }
    .tax-hide {
        content: '-';
        font-size: 12px !important;
        font-weight: normal !important;
        cursor: pointer;
    }
    .tax-title {
        cursor: pointer;
    }
</style>
<?php
$_value = $block->getTotal()->getValue();
$_style = $block->getTotal()->getStyle();
?>
<?php global $taxIter; $taxIter++; ?>

<?php
$attributes = 'class="totals-tax"';
if ($this->helper('Magento\Tax\Helper\Data')->displayFullSummary() && $_value != 0) {
    $attributes = 'class="totals-tax-summary" data-mage-init=\'{"toggleAdvanced": {"selectorsToggleClass": "shown", "baseToggleClass": "expanded", "toggleContainers": ".totals-tax-details"}}\'';
}
?>

<tr <?php /* @escapeNotVerified */ echo $attributes; ?>>
    <th style="<?php /* @escapeNotVerified */ echo $_style ?>" class="mark" colspan="<?php /* @escapeNotVerified */ echo $block->getColspan(); ?>" scope="row">
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayFullSummary()): ?>
            <span class="detailed tax-title"><?php /* @escapeNotVerified */ echo $block->getTotal()->getTitle()?>
                <span class='tax-show'> + </span>
                <span class='tax-hide' style="display:none"> - </span>
            </span>
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo $block->getTotal()->getTitle() ?>
        <?php endif;?>
    </th>
    <td style="<?php /* @escapeNotVerified */ echo $_style ?>" class="amount" data-th="<?php echo $block->escapeHtml($block->getTotal()->getTitle()); ?>">
        <?php /* @escapeNotVerified */ echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_value) ?>
    </td>
</tr>

<?php if ($this->helper('Magento\Tax\Helper\Data')->displayFullSummary() && $_value != 0): ?>
    <?php $isTop = 1; ?>
    <?php $taxInfo = $block->getTotal()->getFullInfo();?>
    <?php if (is_array($taxInfo)) :?>
        <?php foreach ($block->getTotal()->getFullInfo() as $info): ?>
            <?php if (isset($info['hidden']) && $info['hidden']) {
                continue;
            } ?>
            <?php $percent = $info['percent']; ?>
            <?php $amount = $info['amount']; ?>
            <?php $rates = $info['rates']; ?>
            <?php $isFirst = 1; ?>

            <?php foreach ($rates as $rate): ?>
                <tr class="totals-tax-details details-<?php /* @escapeNotVerified */ echo $taxIter; ?>" style="display:none">
                    <th class="mark" style="<?php /* @escapeNotVerified */ echo $_style ?>" colspan="<?php /* @escapeNotVerified */ echo $block->getColspan(); ?>" scope="row">
                        <?php echo $block->escapeHtml($rate['title']); ?>
                        <?php if (!is_null($rate['percent'])): ?>
                            (<?php echo (float)$rate['percent']; ?>%)
                        <?php endif; ?>
                    </th>
                    <?php if ($isFirst): ?>
                        <td style="<?php /* @escapeNotVerified */ echo $_style ?>" class="amount" rowspan="<?php echo count($rates); ?>"
                            data-th="<?php echo $block->escapeHtml($rate['title']); ?><?php if (!is_null($rate['percent'])): ?>(<?php echo (float)$rate['percent']; ?>%)<?php endif; ?>">
                            <?php /* @escapeNotVerified */ echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($amount); ?>
                        </td>
                    <?php endif; ?>
                </tr>
                <?php $isFirst = 0; ?>
                <?php $isTop = 0; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endif;?>
<?php endif;?>


<script>
    require(['jquery'], function ($) {
        $('.tax-title').click(function(){
            if($('.totals-tax-details').is(':visible')) {
                $('.totals-tax-details').hide();
                $('.tax-show').show();
                $('.tax-hide').hide();
            } else {
                $('.totals-tax-details').show();
                $('.tax-show').hide();
                $('.tax-hide').show();
            }
        });
    });
</script>