<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $url = $block->getReviewsUrl() . '#reviews'; ?>
<?php $urlForm = $block->getReviewsUrl() . '#review-form'; ?>
<?php if ($block->getReviewsCount()): ?>
<?php $rating = $block->getRatingSummary(); ?>
<div class="product-reviews-summary short<?php echo !$rating ? ' no-rating' : ''?>">
    <?php if ($rating):?>
    <div class="ratings">
            <div class="rating-box">
                    <div style="width: <?php /* @escapeNotVerified */ echo $rating; ?>%;" class="rating"></div>
            </div><span>(<?php /* @escapeNotVerified */ echo $block->getReviewsCount() ?>)</span>
    </div>
    <?php endif;?>
</div>
<?php else:?>
<div class="product-reviews-summary short">
<div class="ratings">
<br />    
</div></div>

<?php endif; ?>
