<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<div class="page-title-wrapper">
    <h1 class="page-title" id="page-title-heading" aria-labelledby="page-title-heading toolbar-amount">
        <span class="base" data-ui-id="page-title-wrapper" >contact us</span>
    </h1>
</div>
<div class="widget block block-static-block customer-service">
    <div class="row">
        <div class="col-md-12  col-ms-12 col-xs-12">
            <iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3150.3175070023203!2d144.8307693158796!3d-37.852860644055696!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad66178365e4005%3A0xd053aebc37912130!2s32+Drake+Blvd%2C+Altona+VIC+3018%2C+Australia!5e0!3m2!1sen!2sus!4v1463985643576" width="100%" height="450" frameborder="0"></iframe>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6  col-ms-6 col-xs-12">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-information')->toHtml();?>

        </div>
        <div class="col-md-6 col-ms-6 col-xs-12">
            <form class="form contact"
                  action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
                  id="contact-form"
                  method="post"
                  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
                  data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset">
                    <div class="field note no-label"><?php /* @escapeNotVerified */ echo __('Alternatively, simply fill out the form below and we get back to you as soon as possible.') ?></div>
                    <div class="field name required">
                        <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
                        <div class="control">
                            <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                        </div>
                    </div>
                    <div class="field email required">
                        <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                        <div class="control">
                            <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                        </div>
                    </div>
                    <div class="field telephone">
                        <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                        <div class="control">
                            <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" />
                        </div>
                    </div>
                    <div class="field comment required">
                        <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?></span></label>
                        <div class="control">
                            <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                        </div>
                    </div>
                    <div class="field captcha">
   			 <div class="g-recaptcha" data-sitekey="<?php echo $block->getSiteKey(); ?>"> </div>
                    </div>
                    <?php echo $block->getChildHtml('form.additional.info'); ?>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <input type="hidden" name="hideit" id="hideit" value="" />
                        <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                            <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>